theme: jekyll-theme-cayman
title: The NOVA System
description: a work in progress
author: Garv Shah
markdown: kramdown
baseurl: "/blog"
url: "https://the-nova-system.github.io"
github: [metadata]
permalink: pretty
copyright: Garv Shah

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor/bundle

sass:
  sass_dir: _sass
  style: :compressed

social-network-links:
  email: "gshah.6110@gmail.com"
  github: The-NOVA-System

nav:
  - title: Home
    url: https://the-nova-system.github.io/blog
  - title: Website
    url: https://the-nova-system.github.io

collections:
  posts:
    output: true
    permalink: /posts/:title

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

kramdown:
  math_engine: katex
feed:
  posts_limit: 50
  excerpt_only: true
